import type { Marco } from "./vbmapp-data";

export const MARCOS_NIVEL2: Marco[] = [
  // ── MANDO ──
  { id: "mando_2_6", area: "mando", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Emite 5+ mandos espontâneos por hora em pelo menos 2 ambientes diferentes",
    criterio: "Documentar 5 mandos sem prompting em sessão clínica E em casa ou escola." },
  { id: "mando_2_7", area: "mando", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Manda por atenção, ajuda ou atividade preferida (3 tipos diferentes)",
    criterio: "Observar mandos para atenção ('olha!'), ajuda ('me ajuda') e atividade ('vamos brincar'); 1 de cada." },
  { id: "mando_2_8", area: "mando", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Usa adjetivos em mandos (cor, tamanho, quantidade): 5 exemplos diferentes",
    criterio: "Ex: 'quero o grande', 'mais suco', 'bola vermelha'; 5 combinações distintas observadas." },
  { id: "mando_2_9", area: "mando", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Encadeia mandos em sintagmas de 2+ palavras (20 combinações diferentes)",
    criterio: "Ex: 'quero suco de laranja', 'não quero isso'; 20 combinações distintas registradas." },
  { id: "mando_2_10", area: "mando", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Emite mandos de informação funcionais ('onde está X?', 'o que é isso?', 'como se chama?')",
    criterio: "Pelo menos 3 topografias diferentes de mando de informação usadas espontaneamente." },

  // ── TATO ──
  { id: "tato_2_6", area: "tato", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Tateia 50 objetos, figuras ou eventos diferentes",
    criterio: "Nomear 50 itens distintos; apresentar em lotes de 10 objetos/figuras variados." },
  { id: "tato_2_7", area: "tato", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Tateia ações (10), partes do corpo (8) e propriedades (cor, tamanho, forma — 5 cada)",
    criterio: "Variar entre ações em figuras, partes do corpo e propriedades; critérios individuais por subgrupo." },
  { id: "tato_2_8", area: "tato", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Tateia com adjetivos: nomeia objeto + atributo ('bola vermelha', 'carro grande')",
    criterio: "10 combinações objeto+adjetivo distintas; adjetivos de pelo menos 3 categorias diferentes." },
  { id: "tato_2_9", area: "tato", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Descreve cenas em figuras: nomeia sujeito + ação ('a menina está correndo')",
    criterio: "5 descrições de cena diferentes; cada uma com pelo menos sujeito e verbo." },
  { id: "tato_2_10", area: "tato", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Tateia 100 itens distintos incluindo pelo menos 5 categorias semânticas",
    criterio: "100 tatos distintos no repertório; confirmados por lista com avaliação em múltiplas sessões." },

  // ── OUVINTE ──
  { id: "ouvinte_2_6", area: "ouvinte", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Seleciona 25 objetos ou figuras pelo nome (array de 5)",
    criterio: "25 itens distintos identificados corretamente; array de pelo menos 5 itens durante teste." },
  { id: "ouvinte_2_7", area: "ouvinte", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Segue instruções de 2 passos não relacionados ('pega o lápis e vai para a cadeira')",
    criterio: "5 sequências de 2 instruções diferentes; executar ambos os passos sem repetição." },
  { id: "ouvinte_2_8", area: "ouvinte", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Seleciona itens por LRFFC: 20 diferentes por função, característica ou classe",
    criterio: "Pelo menos 7 de cada tipo (função, característica, classe); array de 5 figuras." },
  { id: "ouvinte_2_9", area: "ouvinte", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Identifica objetos por adjetivos: seleciona o 'grande', o 'vermelho', o 'redondo' (10 adjetivos)",
    criterio: "Com 2 objetos diferindo em 1 atributo, selecionar o correto; 10 adjetivos distintos." },
  { id: "ouvinte_2_10", area: "ouvinte", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Segue instruções com preposições: 'em cima', 'embaixo', 'dentro', 'atrás', 'na frente' (5)",
    criterio: "Executar ação com objeto usando cada preposição; 5 preposições distintas." },

  // ── IMITAÇÃO MOTORA ──
  { id: "imitacao_motora_2_6", area: "imitacao_motora", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Imita 20 ações motoras diferentes com e sem objetos",
    criterio: "Repertório documentado de 20 ações imitadas sem prompting físico." },
  { id: "imitacao_motora_2_7", area: "imitacao_motora", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Imita sequências de 3 ações em cadeia",
    criterio: "Modelo demonstra 3 ações seguidas; criança reproduz na mesma ordem; 3 sequências distintas." },
  { id: "imitacao_motora_2_8", area: "imitacao_motora", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Imita ações de faz de conta com objetos substitutos (ex: banana como telefone)",
    criterio: "3 episódios de imitação simbólica com objetos que não são funcionalmente o item representado." },
  { id: "imitacao_motora_2_9", area: "imitacao_motora", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Imita movimentos de pares em brincadeiras motoras (roda, dança, imitação recíproca)",
    criterio: "2 episódios observados de imitação motora iniciada pelo par; sem modelo do adulto." },
  { id: "imitacao_motora_2_10", area: "imitacao_motora", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Imita movimentos oromotores e faciais: 5 diferentes (ex: estalar língua, franzir testa)",
    criterio: "Modelo facial demonstrado ao vivo; criança imita 5 movimentos distintos." },

  // ── ECOICO ──
  { id: "ecoico_2_6", area: "ecoico", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Repete 50+ palavras diferentes com ≥50% de inteligibilidade para estranhos",
    criterio: "50 palavras distintas; apresentar a avaliador não familiar; comprensível em metade das tentativas." },
  { id: "ecoico_2_7", area: "ecoico", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Repete frases de 3 palavras (10 diferentes) com acurácia ≥80%",
    criterio: "10 frases de 3 palavras; correto em 8 de 10 tentativas por frase." },
  { id: "ecoico_2_8", area: "ecoico", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Repete frases de 4-5 palavras após ouvir uma vez",
    criterio: "5 frases de 4-5 palavras repetidas após apresentação única; sem modelo repetido." },
  { id: "ecoico_2_9", area: "ecoico", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Repete músicas e rimas infantis conhecidas com letra inteligível",
    criterio: "3 músicas ou rimas completas repetidas após modelo ou em conjunto; letra reconhecível." },
  { id: "ecoico_2_10", area: "ecoico", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Repete enunciados de 5+ palavras mantendo ordem e estrutura gramatical",
    criterio: "5 enunciados de 5+ palavras; manter ordem das palavras e estrutura básica da frase." },

  // ── VPS-MTS ──
  { id: "vps_mts_2_6", area: "vps_mts", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Emparelha por categoria: sorteia 20 itens em 5 categorias diferentes",
    criterio: "20 figuras divididas em 5 categorias; criança agrupa corretamente sem erros." },
  { id: "vps_mts_2_7", area: "vps_mts", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Emparelha itens não idênticos por similaridade funcional (ex: copo ↔ caneca)",
    criterio: "10 pares de itens similares mas não idênticos; selecionar o par correto em array de 5." },
  { id: "vps_mts_2_8", area: "vps_mts", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Completa sequências visuais simples (padrão AB, ABC): 5 sequências",
    criterio: "Apresentar padrão incompleto; criança seleciona o item correto para completar; 5 padrões." },
  { id: "vps_mts_2_9", area: "vps_mts", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Emparelha letras maiúsculas com minúsculas (10 pares) e numerais 1-10",
    criterio: "10 pares de letras maiúscula/minúscula e 10 numerais emparelhados corretamente." },
  { id: "vps_mts_2_10", area: "vps_mts", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Classifica objetos por 2 atributos simultâneos (cor E forma): 10 itens",
    criterio: "Ex: separar apenas os círculos vermelhos de um conjunto misto; 10 itens corretos." },

  // ── BRINCAR INDEPENDENTE ──
  { id: "brincar_independente_2_6", area: "brincar_independente", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Brinca de forma funcional com 10 brinquedos diferentes",
    criterio: "10 brinquedos distintos usados de maneira funcional e intencional; documentar em observação." },
  { id: "brincar_independente_2_7", area: "brincar_independente", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Organiza e sequencia brincadeiras funcional por 10 minutos sem interrupção",
    criterio: "Sequência de atividades com brinquedos por 10 min sem precisar de redirecionamento adulto." },
  { id: "brincar_independente_2_8", area: "brincar_independente", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Engaja em 5 episódios de brincadeira simbólica diferente (faz de conta elaborado)",
    criterio: "5 temas distintos de faz de conta (cozinha, médico, escola, etc.); pelo menos 3 ações por episódio." },
  { id: "brincar_independente_2_9", area: "brincar_independente", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Usa criatividade e variação: adapta brincadeira com materiais disponíveis",
    criterio: "Observar 3 episódios em que a criança adapta ou cria variação na brincadeira espontaneamente." },
  { id: "brincar_independente_2_10", area: "brincar_independente", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Sustenta episódio de faz de conta temático por 5+ minutos com sequência coerente",
    criterio: "Um episódio contínuo de faz de conta por ≥5 min; sequência de ações relacionadas e coerentes." },

  // ── COMPORTAMENTO SOCIAL ──
  { id: "comportamento_social_2_6", area: "comportamento_social", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Inicia interação com par de forma espontânea (aproximação, oferta de brinquedo, verbalização)",
    criterio: "Criança inicia — não o par — pelo menos 3 vezes em uma sessão de 30 min com pares disponíveis." },
  { id: "comportamento_social_2_7", area: "comportamento_social", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Compartilha materiais com par sem resistência: 3 episódios observados",
    criterio: "Ceder item a par quando solicitado ou espontaneamente; 3 ocorrências sem choro ou recusa." },
  { id: "comportamento_social_2_8", area: "comportamento_social", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Mantém turnos em brincadeiras simples com par (mínimo 5 trocas consecutivas)",
    criterio: "Jogo de turnos (rolar bola, blocos, etc.); ≥5 trocas consecutivas sem interrupção." },
  { id: "comportamento_social_2_9", area: "comportamento_social", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Responde a convites de pares ('quer brincar?', 'vem aqui'): 3 respostas diferentes",
    criterio: "Aceitar convite de par e engajar em atividade proposta; 3 situações distintas observadas." },
  { id: "comportamento_social_2_10", area: "comportamento_social", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Brinca cooperativamente com 1 par por 5+ minutos em atividade compartilhada",
    criterio: "Brincadeira com objetivo comum (não paralela); ≥5 min de cooperação observada." },

  // ── INTRAVERBAL ──
  { id: "intraverbal_2_6", area: "intraverbal", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Nomeia itens de 5 categorias: diz 3+ exemplos por categoria quando perguntado",
    criterio: "Ex: 'Quais são frutas?' → responde com 3+; 5 categorias diferentes." },
  { id: "intraverbal_2_7", area: "intraverbal", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Completa pares de opostos (10): quente/frio, grande/pequeno, etc.",
    criterio: "Terapeuta fala o primeiro; criança completa com o oposto; 10 pares distintos." },
  { id: "intraverbal_2_8", area: "intraverbal", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Descreve função de 20 objetos ('o sapato serve para...')",
    criterio: "Resposta funcional aceitável; 20 objetos distintos; apresentar sem a figura." },
  { id: "intraverbal_2_9", area: "intraverbal", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Responde perguntas 'quem?', 'onde?' e 'quando?' simples (5 de cada)",
    criterio: "Perguntas sobre rotinas ou histórias familiares; 5 respostas funcionais de cada tipo." },
  { id: "intraverbal_2_10", area: "intraverbal", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Mantém tópico de conversação por 3+ trocas consecutivas sobre assunto familiar",
    criterio: "Terapeuta inicia tema; criança mantém com respostas relacionadas; 3 pares pergunta-resposta." },

  // ── LRFFC ──
  { id: "lrffc_2_6", area: "lrffc", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Seleciona 25 itens diferentes por função, característica ou classe (array de 10)",
    criterio: "Array aumentado para 10 figuras; 25 seleções corretas variando os 3 tipos de relação." },
  { id: "lrffc_2_7", area: "lrffc", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Seleciona item correto com 2 atributos na instrução ('o animal que voa e é pequeno')",
    criterio: "Instrução com 2 restrições; 10 itens corretos com atributos duplos." },
  { id: "lrffc_2_8", area: "lrffc", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Identifica o item que NÃO pertence à categoria (5 conjuntos diferentes)",
    criterio: "Conjunto de 4 figuras; 1 não pertence; criança indica o intruso; 5 conjuntos distintos." },
  { id: "lrffc_2_9", area: "lrffc", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Agrupa 30 figuras em 6 categorias sem instrução explícita de qual categoria",
    criterio: "Criança categoriza espontaneamente; aceitar reagrupamentos funcionais coerentes." },
  { id: "lrffc_2_10", area: "lrffc", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Seleciona item por descrição de 3 características ('é redondo, é de comer e é amarelo')",
    criterio: "Descrição verbal de 3 atributos sem figura de amostra; 10 seleções corretas." },

  // ── LEITURA ──
  { id: "leitura_2_6", area: "leitura", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Lê 10 palavras funcionais em voz alta com precisão (seu nome, saída, banheiro, etc.)",
    criterio: "10 palavras de uso cotidiano lidas corretamente em voz alta; sem figura como pista." },
  { id: "leitura_2_7", area: "leitura", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Associa 10 palavras escritas a definições simples ou figuras relacionadas (não idênticas)",
    criterio: "Ex: 'frio' → figura de sorvete; 10 pares palavra-conceito distintos." },
  { id: "leitura_2_8", area: "leitura", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Lê e executa frases simples de instrução de 1 passo ('pegue o lápis'): 10 frases",
    criterio: "Ler frase em silêncio e executar a ação; 10 frases de instrução distintas." },
  { id: "leitura_2_9", area: "leitura", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Responde 3 perguntas de compreensão sobre texto de 2-3 frases lido",
    criterio: "Texto simples sobre tema conhecido; 3 perguntas literais respondidas corretamente." },
  { id: "leitura_2_10", area: "leitura", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Lê 25 palavras variadas em voz alta com ≥80% de acurácia",
    criterio: "Lista de 25 palavras de 1-3 sílabas; pelo menos 20 lidas corretamente." },

  // ── ESCRITA ──
  { id: "escrita_2_6", area: "escrita", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Copia palavras de 3-4 letras com modelo visual presente",
    criterio: "5 palavras copiadas; letras reconhecíveis e na ordem correta; modelo visível." },
  { id: "escrita_2_7", area: "escrita", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Escreve o próprio nome completo sem modelo",
    criterio: "Nome completo legível sem cópia ou traçado guiado; aceitar letra de forma." },
  { id: "escrita_2_8", area: "escrita", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Copia frases simples de 3-5 palavras com letra legível",
    criterio: "3 frases copiadas; palavras separadas e letras reconhecíveis por leitor familiarizado." },
  { id: "escrita_2_9", area: "escrita", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Escreve 5 palavras conhecidas sob ditado (sem modelo visual)",
    criterio: "Terapeuta fala a palavra; criança escreve; 5 palavras distintas; ≥80% das letras corretas." },
  { id: "escrita_2_10", area: "escrita", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Escreve 10 palavras familiares de memória (sem ditado e sem modelo)",
    criterio: "Pedir que escreva palavras que sabe; 10 palavras distintas e legíveis produzidas." },

  // ── MATEMÁTICA ──
  { id: "matematica_2_6", area: "matematica", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Conta e informa quantidade de grupos de 1-5 objetos com correspondência um a um",
    criterio: "Apresentar grupos variados de 1-5 objetos; criança conta e diz o total; 5 grupos distintos." },
  { id: "matematica_2_7", area: "matematica", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Lê e nomeia numerais de 1 a 10 corretamente",
    criterio: "Apresentar numerais fora de ordem; criança nomeia; todos os 10 numerais." },
  { id: "matematica_2_8", area: "matematica", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Compara grupos usando 'mais', 'menos' e 'igual' (10 comparações)",
    criterio: "Dois grupos de objetos (quantidades 1-5); criança compara corretamente; 10 pares." },
  { id: "matematica_2_9", area: "matematica", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Realiza adição com objetos concretos: resultados até 5 (10 somas)",
    criterio: "Juntar dois grupos físicos e contar o total; 10 operações distintas; resultados ≤5." },
  { id: "matematica_2_10", area: "matematica", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Identifica e continua sequência numérica simples (1-10): completar o número faltante",
    criterio: "5 sequências com 1 número faltante; criança identifica e diz ou escreve o número correto." },

  // ── HABILIDADES DE GRUPO ──
  { id: "habilidades_grupo_2_6", area: "habilidades_grupo", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Permanece engajado em atividade de grupo por 10 minutos sem comportamentos disruptivos",
    criterio: "Grupo de 3+ pessoas; criança participa ou acompanha sem fuga, grito ou agressão por 10 min." },
  { id: "habilidades_grupo_2_7", area: "habilidades_grupo", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Aguarda sua vez em atividade de grupo sem prompting: 3 episódios",
    criterio: "Esperar pela vez sem precisar de lembrete verbal; 3 turnos observados em contexto de grupo." },
  { id: "habilidades_grupo_2_8", area: "habilidades_grupo", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Segue rotinas de grupo sem prompting (roda, calendário, lanche, saída)",
    criterio: "Observar 3 rotinas distintas; criança acompanha o grupo sem instrução individual." },
  { id: "habilidades_grupo_2_9", area: "habilidades_grupo", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Responde quando chamado pelo terapeuta/professor em contexto de grupo (não individualmente)",
    criterio: "Chamada pelo nome em grupo; criança responde (olha, levanta a mão, responde); ≥5 vezes." },
  { id: "habilidades_grupo_2_10", area: "habilidades_grupo", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Participa ativamente de 3 tipos diferentes de atividade em grupo (jogo, roda, lição)",
    criterio: "3 formatos distintos de atividade coletiva; participação funcional e adequada observada." },

  // ── ESTRUTURA LINGUÍSTICA ──
  { id: "estrutura_linguistica_2_6", area: "estrutura_linguistica", nivel: 2, item: 6, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Usa frases de 3+ palavras espontaneamente em mandos e tatos",
    criterio: "10 frases de 3+ palavras distintas observadas em contexto natural; qualquer função verbal." },
  { id: "estrutura_linguistica_2_7", area: "estrutura_linguistica", nivel: 2, item: 7, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Usa pronomes pessoais adequadamente: eu, você, ele/ela (5 situações cada)",
    criterio: "Uso correto e espontâneo de cada pronome em contexto; 5 ocorrências por pronome." },
  { id: "estrutura_linguistica_2_8", area: "estrutura_linguistica", nivel: 2, item: 8, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Usa plural e possessivos espontaneamente: 10 ocorrências de cada",
    criterio: "Plural regular (livros, bolas) e possessivos (meu, minha, do) em contexto espontâneo." },
  { id: "estrutura_linguistica_2_9", area: "estrutura_linguistica", nivel: 2, item: 9, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Formula perguntas espontâneas: 'o que é isso?', 'onde está?', 'por quê?' (3 tipos)",
    criterio: "Perguntas genuínas (busca informação); 5 ocorrências de cada tipo." },
  { id: "estrutura_linguistica_2_10", area: "estrutura_linguistica", nivel: 2, item: 10, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Usa conectivos 'e', 'mas', 'porque' em frases espontâneas: 5 de cada",
    criterio: "Uso funcional e gramaticalmente adequado; 5 ocorrências de cada conectivo observadas." },
];
