import type { Marco } from "./vbmapp-data";

export const MARCOS_NIVEL3: Marco[] = [
  // ── MANDO ──
  { id: "mando_3_11", area: "mando", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Manda por informação em contextos variados e com diferentes parceiros (5 tipos)",
    criterio: "Mandos de informação (onde, o que, quem, como, quando) em 5 situações naturais distintas." },
  { id: "mando_3_12", area: "mando", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Usa mandos sociais funcionais: 'me ajuda', 'pode repetir?', 'espera um pouco'",
    criterio: "3 topografias de mando social distintas; uso espontâneo e contextualmente adequado." },
  { id: "mando_3_13", area: "mando", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Encadeia mandos para obter resultado complexo (sequência de 3+ mandos relacionados)",
    criterio: "Ex: 'vai lá', 'pega o suco', 'traz pra mim'; sequência de mandos para 1 objetivo; 3 episódios." },
  { id: "mando_3_14", area: "mando", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Usa mandos indiretos e educados: 'posso ter...?', 'você pode...?', 'por favor'",
    criterio: "5 ocorrências de forma polida ou indireta de mando; espontâneas e funcionalmente adequadas." },
  { id: "mando_3_15", area: "mando", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Manda para interação social (não apenas para obter tangível): 'quer brincar?', 'me conta'",
    criterio: "5 mandos cujo reforçador é social (atenção, conversa, brincadeira); sem objeto tangível." },

  // ── TATO ──
  { id: "tato_3_11", area: "tato", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Tateia 200+ itens distintos incluindo ações, propriedades, relações e eventos",
    criterio: "Repertório documentado de 200 tatos; confirmar em avaliação com lista abrangente." },
  { id: "tato_3_12", area: "tato", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Tateia eventos passados e futuros com marcação temporal ('ontem eu fui', 'amanhã vou')",
    criterio: "5 relatos de evento passado e 5 de evento futuro; uso correto de marcação temporal." },
  { id: "tato_3_13", area: "tato", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Tateia emoções em si ('estou com raiva') e em outros ('ele está triste'): 5 emoções distintas",
    criterio: "Nomear emoção em si e em outros; 5 emoções diferentes; uso espontâneo ou mediante pergunta." },
  { id: "tato_3_14", area: "tato", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Tateia relações espaciais (dentro, fora, entre, ao lado) e temporais (antes, depois): 10",
    criterio: "10 relações diferentes; apresentar situações físicas ou figuras; nomear corretamente." },
  { id: "tato_3_15", area: "tato", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Usa adjetivos, advérbios e preposições em tatos espontâneos: 10 ocorrências de cada",
    criterio: "Uso espontâneo de adjetivos (bonito, rápido), advérbios (aqui, agora, devagar) e preposições." },

  // ── OUVINTE ──
  { id: "ouvinte_3_11", area: "ouvinte", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Segue instruções de 3 passos não relacionados sem repetição",
    criterio: "Apresentar 3 instruções de uma vez; executar os 3 sem que o terapeuta repita; 3 sequências." },
  { id: "ouvinte_3_12", area: "ouvinte", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Seleciona itens por descrição elaborada de 4+ atributos sem figura de amostra",
    criterio: "10 descrições de 4 atributos; criança seleciona o item correto em array de 10 figuras." },
  { id: "ouvinte_3_13", area: "ouvinte", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Compreende negação em instrução: 'pega o que NÃO é vermelho' (10 itens)",
    criterio: "10 instruções com negação; criança seleciona corretamente excluindo o item negado." },
  { id: "ouvinte_3_14", area: "ouvinte", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Responde a instruções condicionais simples: 'se X então Y' (5 condicionais)",
    criterio: "Ex: 'se o cartão for vermelho, levante a mão'; 5 condicionais distintas; todas corretas." },
  { id: "ouvinte_3_15", area: "ouvinte", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Demonstra compreensão de história simples lida em voz alta: responde 5 perguntas",
    criterio: "História de 5-8 frases; 5 perguntas literais e inferenciais; acerto em ≥4." },

  // ── IMITAÇÃO MOTORA ──
  { id: "imitacao_motora_3_11", area: "imitacao_motora", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Imita sequências complexas de 4+ ações motoras em cadeia",
    criterio: "Modelo demonstra 4+ ações; criança reproduz na ordem; 3 sequências distintas sem ajuda." },
  { id: "imitacao_motora_3_12", area: "imitacao_motora", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Imita pares em jogos de regras motoras simples (pique, cabo de guerra, amarelinha)",
    criterio: "Participar de 2 jogos de regras seguindo movimentos e regras por observação dos pares." },
  { id: "imitacao_motora_3_13", area: "imitacao_motora", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Copia padrões gráficos complexos: losango, letras cursivas, padrões geométricos (5)",
    criterio: "5 padrões copiados com fidelidade reconhecível; avaliador julgará acurácia." },
  { id: "imitacao_motora_3_14", area: "imitacao_motora", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Aprende 2 jogos novos por observação de pares sem instrução direta do adulto",
    criterio: "Observar pares jogando; criança ingressa e joga corretamente sem o adulto explicar as regras." },
  { id: "imitacao_motora_3_15", area: "imitacao_motora", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Demonstra imitação diferida: reproduz sequência de ação após intervalo de ≥10 min",
    criterio: "Modelo no início da sessão; atraso ≥10 min; criança reproduz sem novo modelo; 3 tentativas." },

  // ── ECOICO ──
  { id: "ecoico_3_11", area: "ecoico", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Repete enunciados de 6-8 palavras com acurácia de ordem e estrutura",
    criterio: "5 enunciados de 6-8 palavras; manter todas as palavras na ordem correta." },
  { id: "ecoico_3_12", area: "ecoico", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Repete músicas, poemas e parlendas extensas com letra e melodia corretas",
    criterio: "3 produções extensas (>10 versos) com letra reconhecível e melodia preservada." },
  { id: "ecoico_3_13", area: "ecoico", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Repete frases com estruturas gramaticais complexas (subordinadas, passivas): 5 frases",
    criterio: "Ex: 'o menino que estava correndo caiu'; 5 frases complexas; estrutura preservada." },
  { id: "ecoico_3_14", area: "ecoico", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Autocorrige pronúncia após feedback: 3 episódios observados",
    criterio: "Adulto sinaliza pronúncia inadequada; criança tenta corrigir; 3 autocorreções espontâneas." },
  { id: "ecoico_3_15", area: "ecoico", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Discrimina e repete pares mínimos fonologicamente similares: 10 pares (ex: pato/gato)",
    criterio: "Ouvir e repetir pares mínimos; criança os distingue e repete cada um corretamente." },

  // ── VPS-MTS ──
  { id: "vps_mts_3_11", area: "vps_mts", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Classifica objetos por 3 atributos simultâneos (cor, forma e tamanho): 10 itens",
    criterio: "Ex: 'separe somente os quadrados grandes azuis'; 10 classificações corretas." },
  { id: "vps_mts_3_12", area: "vps_mts", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Completa padrões visuais com itens faltantes em sequências ABBC, AABB (5 padrões)",
    criterio: "Padrões de 2 variáveis; criança identifica a regra e seleciona o item correto; 5 padrões." },
  { id: "vps_mts_3_13", area: "vps_mts", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Emparelha por relação causal: 5 pares (nuvem→chuva, fósforo→fogo, semente→planta)",
    criterio: "Apresentar figura causa; criança seleciona figura efeito em array de 5; 5 pares causais." },
  { id: "vps_mts_3_14", area: "vps_mts", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Discrimina letras e números visualmente similares: b/d, p/q, 6/9, 3/8 (10 pares)",
    criterio: "Apresentar letra/número; criança nomeia ou emparelha corretamente; 10 discriminações." },
  { id: "vps_mts_3_15", area: "vps_mts", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Completa puzzles de 20+ peças independentemente (3 puzzles diferentes)",
    criterio: "Puzzles de ≥20 peças; concluir cada um sem assistência; dentro de tempo razoável." },

  // ── BRINCAR INDEPENDENTE ──
  { id: "brincar_independente_3_11", area: "brincar_independente", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Engaja em brincadeira temática complexa com vários personagens por 15+ minutos",
    criterio: "Faz de conta com ≥2 personagens e enredo coerente; ≥15 min de engajamento contínuo." },
  { id: "brincar_independente_3_12", area: "brincar_independente", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Usa objetos substitutos no faz de conta: 3 substitutos diferentes em brincadeira",
    criterio: "Ex: régua = espada, caixinha = carro; 3 substituições funcionalmente coerentes observadas." },
  { id: "brincar_independente_3_13", area: "brincar_independente", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Cria roteiro de brincadeira com início, desenvolvimento e desfecho espontâneos",
    criterio: "Brincadeira com 3 fases narrativas reconhecíveis; sem direcionamento adulto; 2 episódios." },
  { id: "brincar_independente_3_14", area: "brincar_independente", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Adapta a brincadeira ao ambiente e materiais disponíveis de forma criativa",
    criterio: "Em ambiente com materiais não-padrão, criança cria brincadeira adequada; 3 observações." },
  { id: "brincar_independente_3_15", area: "brincar_independente", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Joga jogos de regras simples independentemente (memória, dominó, tabuleiro): 2 diferentes",
    criterio: "Jogar seguindo todas as regras sem ajuda do adulto; 2 jogos distintos com regras." },

  // ── COMPORTAMENTO SOCIAL ──
  { id: "comportamento_social_3_11", area: "comportamento_social", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Inicia e mantém conversação com par por 5+ trocas sobre tema de interesse mútuo",
    criterio: "≥5 pares pergunta-resposta consecutivos; manter tema; iniciado pela criança." },
  { id: "comportamento_social_3_12", area: "comportamento_social", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Resolve conflito simples com par verbalmente (sem agressão ou choro): 3 episódios",
    criterio: "Situação de conflito (disputa de brinquedo, turno); criança negocia verbalmente; 3 episódios." },
  { id: "comportamento_social_3_13", area: "comportamento_social", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Demonstra empatia: reconhece e responde à emoção de par (consola, pergunta, ajuda)",
    criterio: "Par demonstra emoção; criança responde de forma socialmente adequada; 3 episódios." },
  { id: "comportamento_social_3_14", area: "comportamento_social", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Convida par para brincadeira e negocia papéis: 3 episódios diferentes",
    criterio: "Criança propõe atividade, atribui papéis e negocia quando par discorda; 3 ocasiões." },
  { id: "comportamento_social_3_15", area: "comportamento_social", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Adapta comportamento às regras sociais do grupo sem instrução direta: 3 contextos",
    criterio: "Ex: falar baixo na biblioteca, esperar fila, cumprimentar; 3 contextos distintos." },

  // ── INTRAVERBAL ──
  { id: "intraverbal_3_11", area: "intraverbal", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Responde 'por quê?' com explicações funcionais: 10 perguntas diferentes",
    criterio: "Ex: 'por que você usa casaco?' → 'porque está frio'; 10 perguntas distintas; respostas coerentes." },
  { id: "intraverbal_3_12", area: "intraverbal", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Descreve sequência de eventos em ordem: histórias de 4+ passos (3 histórias)",
    criterio: "Recontar sequência de atividade cotidiana ou história; ordem correta; 3 histórias distintas." },
  { id: "intraverbal_3_13", area: "intraverbal", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Mantém tópico de conversação por 5+ trocas sobre assunto escolhido pelo par",
    criterio: "Par escolhe tema; criança sustenta com respostas relacionadas; ≥5 pares de troca." },
  { id: "intraverbal_3_14", area: "intraverbal", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Faz perguntas para obter informação nova (não sabe a resposta): 5 situações",
    criterio: "Perguntas genuínas sobre tema desconhecido; não repetição de informação já sabida; 5 episódios." },
  { id: "intraverbal_3_15", area: "intraverbal", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Responde charadas e perguntas abstratas simples ('o que tem dentes mas não morde?')",
    criterio: "5 charadas ou perguntas de raciocínio; acerto em ≥3 após no máximo 1 dica." },

  // ── LRFFC ──
  { id: "lrffc_3_11", area: "lrffc", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Seleciona item por descrição de 3+ características em array de 10 figuras: 15 itens",
    criterio: "Descrição verbal de 3 atributos; array de 10 figuras; 15 seleções corretas." },
  { id: "lrffc_3_12", area: "lrffc", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Identifica exemplos e não-exemplos de conceito abstrato: 5 conceitos",
    criterio: "Ex: 'isso é um veículo?' para avião, cadeira, bicicleta; 5 conceitos; ≥80% de acerto." },
  { id: "lrffc_3_13", area: "lrffc", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Categoriza itens por função E classe simultaneamente: 10 itens",
    criterio: "Ex: separar 'animais que voam'; exige cruzar 2 critérios; 10 classificações corretas." },
  { id: "lrffc_3_14", area: "lrffc", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Completa analogias simples: 'peixe está para água assim como pássaro está para ___'",
    criterio: "5 analogias de relação; criança completa o par correto; sem figura de amostra." },
  { id: "lrffc_3_15", area: "lrffc", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Demonstra compreensão de conceitos opostos e relacionais: 15 pares",
    criterio: "Ex: parte/todo, causa/efeito, mais/menos; 15 pares relacionais distintos respondidos." },

  // ── LEITURA ──
  { id: "leitura_3_11", area: "leitura", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Lê sentenças completas de 5-8 palavras com compreensão: 5 sentenças",
    criterio: "Ler em voz alta e executar ou responder sobre a sentença; 5 sentenças distintas." },
  { id: "leitura_3_12", area: "leitura", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Responde 5 perguntas literais e 2 inferenciais sobre texto de 5-8 frases",
    criterio: "Texto de nível de pré-escola; 5 perguntas literais + 2 'por que você acha que...?'." },
  { id: "leitura_3_13", area: "leitura", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Lê texto em voz alta com entonação, pausas e ritmo adequados: 3 textos",
    criterio: "Avaliador julga fluência e entonação; 3 textos distintos de nível de pré-escola." },
  { id: "leitura_3_14", area: "leitura", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Identifica a ideia principal de texto simples de 8-10 frases",
    criterio: "Após leitura, criança resume com 1-2 frases o tema central; 3 textos diferentes." },
  { id: "leitura_3_15", area: "leitura", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Decodifica palavras novas usando correspondência grafofonêmica: 10 pseudopalavras",
    criterio: "Palavras inventadas seguindo padrões regulares do português; leitura correta de 8/10." },

  // ── ESCRITA ──
  { id: "escrita_3_11", area: "escrita", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Escreve frases completas (sujeito + verbo + objeto) sem modelo: 5 frases",
    criterio: "A partir de figura ou tema dado; frases gramaticalmente reconhecíveis; sem cópia." },
  { id: "escrita_3_12", area: "escrita", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Escreve respostas curtas a perguntas escritas: 5 perguntas",
    criterio: "Ler pergunta escrita; escrever resposta com pelo menos 2 palavras; 5 perguntas distintas." },
  { id: "escrita_3_13", area: "escrita", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Produz texto de 3-5 frases sobre tema dado com coerência temática",
    criterio: "Tema proposto pelo avaliador; texto com 3+ frases; todas relacionadas ao tema." },
  { id: "escrita_3_14", area: "escrita", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Revisa e corrige pelo menos 3 erros simples na própria escrita mediante instrução",
    criterio: "Avaliador indica 'tem um erro aqui'; criança encontra e corrige; 3 erros em textos distintos." },
  { id: "escrita_3_15", area: "escrita", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Escreve texto criativo breve com início, meio e fim: 2 textos espontâneos",
    criterio: "Sem tema imposto; texto de ≥4 frases com estrutura narrativa reconhecível; 2 produções." },

  // ── MATEMÁTICA ──
  { id: "matematica_3_11", area: "matematica", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Realiza adição e subtração com objetos: resultados até 10 (10 operações cada)",
    criterio: "Operações com manipulativos; 10 adições e 10 subtrações distintas; resultados ≤10." },
  { id: "matematica_3_12", area: "matematica", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "T",
    descricao: "Resolve 5 problemas simples de adição em contexto cotidiano narrado",
    criterio: "Ex: 'você tem 3 balas e ganha mais 2; quantas tem?'; 5 problemas orais distintos." },
  { id: "matematica_3_13", area: "matematica", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Identifica e nomeia moedas (5, 10, 25, 50 centavos, 1 real) e cédulas comuns",
    criterio: "Moedas e cédulas reais ou figuras; nomeação e identificação de cada uma." },
  { id: "matematica_3_14", area: "matematica", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Mede comprimentos com régua e estima quantidades: 5 medições",
    criterio: "Usar régua de 15 cm; medir 5 objetos; resultado com erro ≤1 cm; + 5 estimativas de quantidade." },
  { id: "matematica_3_15", area: "matematica", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "T",
    descricao: "Compreende frações simples com objetos concretos: metade, terço, quarto (5 situações)",
    criterio: "Ex: dividir maçã ao meio; identificar 1/4 de uma pizza; 5 situações com objetos reais." },

  // ── HABILIDADES DE GRUPO ──
  { id: "habilidades_grupo_3_11", area: "habilidades_grupo", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Lidera atividade de grupo quando solicitado: 2 episódios diferentes",
    criterio: "Assumir papel de líder (instruir, organizar, dar turnos) em 2 atividades; grupo de ≥3 pares." },
  { id: "habilidades_grupo_3_12", area: "habilidades_grupo", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Segue regras de 2 jogos em grupo com pares sem necessidade de lembretes",
    criterio: "Jogar com pares seguindo todas as regras; sem precisar que adulto corrija ou relembre." },
  { id: "habilidades_grupo_3_13", area: "habilidades_grupo", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Trabalha em projeto coletivo com 2+ pares por 15+ minutos com divisão de função",
    criterio: "Ex: montar maquete em grupo; cada um com papel; 15 min; cooperação observada." },
  { id: "habilidades_grupo_3_14", area: "habilidades_grupo", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Apresenta trabalho, objeto ou ideia para o grupo de forma inteligível",
    criterio: "Apresentação oral de 3-5 frases para grupo de ≥3; conteúdo compreensível; 2 apresentações." },
  { id: "habilidades_grupo_3_15", area: "habilidades_grupo", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Demonstra comportamentos pró-sociais espontâneos: ajudar, elogiar, cooperar (5 episódios)",
    criterio: "Cada comportamento sem solicitação do adulto; 5 episódios distintos de pró-sociabilidade." },

  // ── ESTRUTURA LINGUÍSTICA ──
  { id: "estrutura_linguistica_3_11", area: "estrutura_linguistica", nivel: 3, item: 11, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Usa orações subordinadas espontaneamente: 'quando', 'porque', 'se' (5 de cada)",
    criterio: "Uso funcional em contexto natural; 5 ocorrências de cada conjunção subordinativa." },
  { id: "estrutura_linguistica_3_12", area: "estrutura_linguistica", nivel: 3, item: 12, pontuacaoMaxima: 0.5, codigo: "O",
    descricao: "Narra eventos passados com sequência temporal correta: 3 relatos de ≥4 eventos",
    criterio: "Relato de evento cotidiano; eventos em ordem cronológica; uso de marcadores (primeiro, depois)." },
  { id: "estrutura_linguistica_3_13", area: "estrutura_linguistica", nivel: 3, item: 13, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Usa futuro simples e condicional em contexto conversacional: 5 ocorrências de cada",
    criterio: "Ex: 'vou brincar depois', 'se chover, não saio'; uso espontâneo e contextualmente correto." },
  { id: "estrutura_linguistica_3_14", area: "estrutura_linguistica", nivel: 3, item: 14, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Demonstra compreensão e uso de ironia ou humor verbal simples: 3 episódios",
    criterio: "Identificar que algo foi dito de forma irônica, ou produzir piada/trocadilho simples; 3 episódios." },
  { id: "estrutura_linguistica_3_15", area: "estrutura_linguistica", nivel: 3, item: 15, pontuacaoMaxima: 1, codigo: "O",
    descricao: "Produz discurso narrativo coerente com 5+ sentenças sobre tema livre",
    criterio: "Narrativa espontânea; coerência temática e coesão entre as frases; 5+ sentenças distintas." },
];
